# GitHub Pages Configuration
title: "Tiation CMS"
description: "Enterprise-grade headless CMS for industry-specific content management"
url: "https://tiation.github.io"
baseurl: "/tiation-cms"

# Theme
theme: minima
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Author information
author:
  name: Tiation
  email: tiatheone@protonmail.com
  
# GitHub
github_username: tiation
repository: "https://github.com/tiation/tiation-cms"

# Settings
future: false
show_excerpts: true
show_dir_listing: true
